name: RestorePipeline_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: 'projectsToRestore'
    displayName: 'Projects to Restore (Source)'
    type: string
    default: 'USNovaRailWay'
  
  - name: 'targetProject'
    displayName: 'Target Project Name'
    type: string
    default: '<same>'
  
  - name: 'targetOrganizationUrl'
    displayName: 'Target Organization URL (<same> = same org)'
    type: string
    default: '<same>'  # <same> = use source org, or specify URL like 'https://dev.azure.com/MyOrg'
  
  - name: 'targetPat'
    displayName: 'Target PAT (<source> = use source PAT)'
    type: string
    default: '<source>'  # <source> = use source PAT, or specify different PAT
  
  - name: 'dryRun'
    displayName: 'Dry Run (Preview Changes)'
    type: boolean
    default: false
  

  - name: 'maxParallelism'
    displayName: 'Maximum Parallel Operations'
    type: number
    default: 4
  - name: 'restoreAll'
    displayName: 'Restore All Components'
    type: boolean
    default: false
  
  - name: 'includeGit'
    displayName: 'Include Git Repositories'
    type: boolean
    default: false
  
  - name: 'includeBuilds'
    displayName: 'Include Build Definitions'
    type: boolean
    default: true
  
  - name: 'includeWorkItems'
    displayName: 'Include Work Items'
    type: boolean
    default: false
  
  - name: 'includeVariables'
    displayName: 'Include Pipeline Variables'
    type: boolean
    default: false
  
  - name: 'includeQueries'
    displayName: 'Include Shared Queries'
    type: boolean
    default: false
  
  - name: 'includeServiceConnections'
    displayName: 'Include Service Connections'
    type: boolean
    default: false
  
  - name: 'includePullRequests'
    displayName: 'Include Pull Requests'
    type: boolean
    default: false
  
  # Git-specific options
  - name: 'gitRepositories'
    displayName: 'Git Repositories (comma-separated, * = all)'
    type: string
    default: '*'  # * = all repositories, or specify comma-separated names
  
  - name: 'pullRequestIds'
    displayName: 'Pull Request IDs (comma-separated, * = all)'
    type: string
    default: '*'  # * = all pull requests, or specify comma-separated IDs
  
  # Build-specific options
  - name: 'buildDefinitions'
    displayName: 'Build Definitions (comma-separated, * = all)'
    type: string
    default: '*'  # * = all definitions, or specify comma-separated names
  
  - name: 'serviceConnections'
    displayName: 'Service Connections (comma-separated, * = all)'
    type: string
    default: '*'  # * = all service connections, or specify comma-separated names
  
  # Work Items-specific options
  - name: 'workItemIds'
    displayName: 'Work Item IDs (comma-separated, * = all)'
    type: string
    default: '*'  # * = all work items, or specify comma-separated IDs
  
  - name: 'bypassRules'
    displayName: 'Bypass Work Item Validation Rules'
    type: boolean
    default: true
  
  # Queries-specific options
  - name: 'queriesFolderPath'
    displayName: 'Queries Folder Path (* = all)'
    type: string
    default: '*'  # * = all queries, or specify folder path like 'Shared Queries/Team A'

trigger: none

pool:
  #vmImage: 'windows-latest'
  name: 'Default'

variables:
  - group: 'ADO Backup Restore'  
  - name: 'buildConfiguration'
    value: 'Debug'
  - name: 'dotnetVersion'
    value: '9.0.x'

jobs:
- job: RestoreJob
  displayName: 'Restore Azure DevOps'

  steps:  
    - checkout: Self
      persistCredentials: true   

    - task: AzureDevOpsRestoreTask@0
      displayName: 'Perform Azure DevOps Restore'
      env:
        ADOBACKUP_LICENSE_KEY: $(Backup.LicenseKey) 
      inputs:
        BackupLicenseKey: '$(Backup.LicenseKey)'
        Pat: '$(Backup.AdoPat.RW)'  #'$(System.AccessToken)'
        BackupRoot: '$(Backup.Root)'
        Projects: '${{ parameters.projectsToRestore }}'  # Source project(s) from backup
        MaxParallelism: '${{ parameters.maxParallelism }}'
        TargetProject: '${{ parameters.targetProject }}'  # Target project to restore into
        ${{ if ne(parameters.targetOrganizationUrl, '') }}:
          TargetOrganizationUrl: '${{ parameters.targetOrganizationUrl }}'
        ${{ if ne(parameters.targetPat, '') }}:
          TargetPat: '${{ parameters.targetPat }}'
        DryRun: ${{ parameters.dryRun }}  # Set to true to preview changes without applying them
        Verbose: true
        
        # Component selection - use include-based flags (v0.6.0+)
        RestoreAll: ${{ parameters.restoreAll }}
        IncludeGit: ${{ parameters.includeGit }}
        IncludeBuilds: ${{ parameters.includeBuilds }}
        IncludeWorkItems: ${{ parameters.includeWorkItems }}
        IncludeVariables: ${{ parameters.includeVariables }}
        IncludeQueries: ${{ parameters.includeQueries }}
        IncludeServiceConnections: ${{ parameters.includeServiceConnections }}
        IncludePullRequests: ${{ parameters.includePullRequests }}
        
        # Git-specific options
        GitRepositories: '${{ parameters.gitRepositories }}'
        PullRequestIds: '${{ parameters.pullRequestIds }}'
        
        # Build-specific options
        BuildDefinitions: '${{ parameters.buildDefinitions }}'
        ServiceConnections: '${{ parameters.serviceConnections }}'
        
        # Work Items-specific options
        WorkItemIds: '${{ parameters.workItemIds }}'
        
        # Queries-specific options
        QueriesFolderPath: '${{ parameters.queriesFolderPath }}'

    # Upload CLI log files for troubleshooting and audit trail
    - task: PublishBuildArtifacts@1
      displayName: 'Upload Restore Logs'
      condition: always()  # Upload logs even if restore fails
      inputs:
        PathtoPublish: '$(Backup.Root)/logs'
        ArtifactName: 'RestoreLogs-$(Build.BuildNumber)'
        publishLocation: 'Container'
      continueOnError: true  # Don't fail pipeline if logs can't be uploaded



